version: "3.7"

services:
  profile-frontend:
    image: "profile-client:latest"
    container_name: "profile-frontend"
    tty: true
    ports: 
      - "3000:3000"
    restart: always

  profile-backend:
    image: "profile-backend:latest"
    container_name: "profile-backend"
    environment:
      - DB_HOST=db
    ports: 
      - "8080:8080"
    restart: always

networks: 
  default:
    name: profile-app-network
