version: "3.7"

services:
  db:
    image: "postgres:11.5"
    container_name: "postgres-db1"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=profiles

networks: 
  default:
    name: profile-app-network
