export const ADD_NEW_PROFILE = 'ADD_NEW_PROFILE';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const GET_ALL_PROFILES = 'GET_ALL_PROFILES';
export const GET_PROFILE = 'GET_PROFILE';
export const CANCEL_SELECTED_PROFILE = 'CANCEL_SELECTED_PROFILE'